### ISSUE TITLE
Any text like Requires level 60 or Requires: Warrior that would be colored red if unfulfilled, is just colored white instead

### ISSUE THREAD

**Issue by refaim** [Zebouski/MoPGearTooltips#1]
MoPGearTooltips prints item requirements (level, reputation) in white color even if I don't meet those requirements yet.

My character
![image](https://user-images.githubusercontent.com/55476/236305005-53ae2768-1803-48e6-8e7a-032b9a934534.png)

Item with modified tooltip that requires 23 lvl
![image](https://user-images.githubusercontent.com/55476/236305066-ccd0dcae-584a-4ce2-bd99-29911bad4c21.png)

Some other item that requires 22 lvl
![image](https://user-images.githubusercontent.com/55476/236305146-a12dbd71-4f97-4bf5-bdb0-9b6219250980.png)

**Comment by Zebouski** [comment]
This is in the known issues readme.

If any developer more experienced than me, knows how I can GetText with the colors, so that I can preserve them in my tooltip rebuilding code, then yes we can fix this bug. But yeah idk how.

**Comment by refaim** [comment]
You can call the `GetTextColor()` method on the same object that you call `GetText()` on.

![image](https://user-images.githubusercontent.com/55476/236380801-89968b4a-efda-4a93-bb5e-17787ea76665.png)

(this description is taken from book "World of Warcraft Programming. A Guide and Reference for Creating WoW Addons", page 1133)

I tested it on Phoenix Pants and it seems to work:
![image](https://user-images.githubusercontent.com/55476/236381010-641af17a-d83e-4e30-816a-b9b6ec579cb9.png)
I printed it as "(r, g, b) a", so the text is originally green, as it should be.

**Comment by Zebouski** [comment]
Fixed in https://github.com/Zebouski/MoPGearTooltips/commit/540931705cf1d544b31dd013b0916b35dda22905
![image](https://github.com/Zebouski/MoPGearTooltips/assets/11151284/c256062a-1b06-4baa-8bdc-ed7be3fb40c8)
![image](https://github.com/Zebouski/MoPGearTooltips/assets/11151284/d2e2b756-7cc8-4a99-bc30-8633059e3af3)
![image](https://github.com/Zebouski/MoPGearTooltips/assets/11151284/137a2f97-ea2e-4a8f-a427-9c741c92cf89)
![image](https://github.com/Zebouski/MoPGearTooltips/assets/11151284/9c11a658-c9c6-42a1-87e9-8f3570b0bb4b)

The main thing i learned is that text color is managed in 2 different ways. Via these Set/Get text color methods, and via |c codes. If you do the |c codes, there's no need for the text color methods as they are transfered to and from the get/set text methods, but blizzard's code uses the get/set textcolor methods instead, so we at least have to get with those.

I chose to keep it consistent and Set the colors that I Get with the same method.
