### ISSUE TITLE
Breaks the tooltip when opening mail 

### ISSUE THREAD

**Issue by akidraham** [Zebouski/MoPGearTooltips#6]
Hi ZaaS i got this error when i open mail, and the tooltip doesnt show for items in mail

Addon enabled
Master Control Program
MoP Gear Tooltips
LFT
pfQuest
pfQuest (TurtleWoW DB)
pfUI 
pfUI (TurtleWoW skins)
pfUI (Addon Skinner)
pfUI (Elite Overlay)

![WoW_4afHKfB6P7](https://user-images.githubusercontent.com/102669236/236624674-0065663f-09cf-4f02-b18f-0d91b0531566.png)

This is with only enabled
Master Control Program
MoP Gear Tooltips
LFT

![WoW_vxTYNtQhgv](https://user-images.githubusercontent.com/102669236/236624708-677f4599-7df8-4c63-833e-a9b180f3d499.png)

**Comment by Zebouski** [comment]
Yep it seems the tooltip references that the mailbox use are different than the rest? I don't quite understand it yet. I will dig in further to how shaguvalue does this correctly while mine doesn't.

**Comment by Zebouski** [comment]
Fixed in https://github.com/Zebouski/MoPGearTooltips/commit/845c8c2aa0a15f75660a417f3eacb8dcbd89b93f
![image](https://github.com/Zebouski/MoPGearTooltips/assets/11151284/267f31b7-3194-4416-a17c-84c639b17261)

When i copied over shaguvalue's tooltip hooking code, I had simply missed copying over a function that the mailbox tooltip hook needed.
